### ISSUE TITLE
Change License

### ISSUE THREAD

**Issue by sirinath** [ISCPIF/openmole#2]
Is i possible to change the license to something like ASL 2.0

**Comment by romainreuillon** [comment]
What would be the point?

**Comment by sirinath** [comment]
You can reuse parts of the technology in commercial applications.

**Comment by romainreuillon** [comment]
This "discution" is too general and does'nt seem to be linked to OpenMOLE. If you which open a new stream and be more spécific to OpenMOLE and to your need.
